apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "adictiz-events-api.fullname" . }}
    labels:
    {{- include "adictiz-events-api.labels" . | nindent 8 }}
data:
    APP_ENV: {{ .Values.php.env.appEnv | quote }}
    APP_DEBUG: {{ .Values.php.env.appDebug | quote }}
    TRUSTED_HOSTS: {{ .Values.php.env.trustedHosts | quote }}
    TRUSTED_PROXIES: "{{ join "," .Values.php.env.trustedProxies }}"
