apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "adictiz-events-api.fullname" . }}-grafana-datasources
    labels:
        grafana_datasource: "1"
data:
    loki-datasource.yaml: |
        apiVersion: 1
        datasources:
            - name: Loki
              type: loki
              access: proxy
              url: "http://{{ .Values.loki.fullnameOverride }}:{{ .Values.loki.loki.server.http_listen_port }}"
              version: 1
              isDefault: false
