apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "adictiz-events-api.fullname" . }}
    labels:
    {{- include "adictiz-events-api.labels" . | nindent 8 }}
spec:
    replicas: 1
    selector:
        matchLabels:
        {{- include "adictiz-events-api.selectorLabels" . | nindent 12 }}
    template:
        metadata:
            annotations:
                checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
                checksum/config-php-fpm: {{ include (print $.Template.BasePath "/configmap-php-fpm.yaml") . | sha256sum }}
                checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
                checksum/secret-jwt-keys: {{ include (print $.Template.BasePath "/secrets-jwt-keys.yaml") . | sha256sum }}
            labels:
            {{- include "adictiz-events-api.labels" . | nindent 16 }}
        spec:
            serviceAccountName: {{ include "adictiz-events-api.serviceAccountName" . }}
            volumes:
                - name: jwt-keys
                  secret:
                      secretName: {{ include "adictiz-events-api.fullname" . }}-jwt-keys
                - name: php-fpm-app-conf
                  configMap:
                      name: {{ include "adictiz-events-api.fullname" . }}-php-fpm
                      items:
                          -   key: app-conf
                              path: app.conf
                - name: php-fpm-app-ini
                  configMap:
                      name: {{ include "adictiz-events-api.fullname" . }}-php-fpm
                      items:
                          -   key: app-ini
                              path: app.ini
                - name: php-run
                  emptyDir: {}
            initContainers:
                - name: php-fpm-exporter
                  image: hipages/php-fpm_exporter:2.2.0
                  restartPolicy: Always
                  env:
                      - name: PHP_FPM_SCRAPE_URI
                        value: "unix:///run/php/php-fpm.sock;/status"
                      - name: PHP_FPM_FIX_PROCESS_COUNT
                        value: "true"
                      - name: PHP_FPM_LOG_LEVEL
                        value: "debug"
                  volumeMounts:
                      - name: php-run
                        mountPath: /run/php
                  ports:
                      - name: exporter
                        containerPort: 9253
                        protocol: TCP
                  readinessProbe:
                    httpGet:
                        path: /metrics
                        port: exporter
                    initialDelaySeconds: 15
                    periodSeconds: 5
                  livenessProbe:
                    httpGet:
                        path: /metrics
                        port: exporter
                    initialDelaySeconds: 15
                    periodSeconds: 5
            containers:
                -   name: {{ .Chart.Name }}
                    image: "{{ .Values.php.image.registry }}/{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
                    imagePullPolicy: {{ .Values.php.image.pullPolicy }}
                    envFrom:
                        -   configMapRef:
                                name: {{ include "adictiz-events-api.fullname" . }}
                        -   secretRef:
                                name: {{ include "adictiz-events-api.fullname" . }}
                    volumeMounts:
                        -   name: php-fpm-app-conf
                            mountPath: /usr/local/etc/php-fpm.d
                            readOnly: true
                        -   name: php-fpm-app-ini
                            mountPath: /usr/local/etc/php.conf.d
                            readOnly: true
                        -   name: php-run
                            mountPath: /run/php
                        -   name: jwt-keys
                            mountPath: /srv/app/config/jwt
                            readOnly: true
                    ports:
                        -   name: http
                            containerPort: 9000
                            protocol: TCP
                    livenessProbe:
                        tcpSocket:
                            port: http
                        initialDelaySeconds: 15
                        periodSeconds: 5
                    readinessProbe:
                        tcpSocket:
                            port: http
                        initialDelaySeconds: 15
                        periodSeconds: 5
                    resources:
                        requests:
                            cpu: 250m
                            memory: 256Mi
                            ephemeral-storage: 200Mi
                        limits:
                            cpu: 375m
                            memory: 384Mi
                            ephemeral-storage: 1Gi
