apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: {{ include "adictiz-events-api.fullname" . }}
    labels:
    {{- include "adictiz-events-api.labels" . | nindent 8 }}
spec:
    selector:
        matchLabels:
        {{- include "adictiz-events-api.selectorLabels" . | nindent 12 }}
    podMetricsEndpoints:
        - port: exporter
          path: /metrics
