apiVersion: v1
kind: Secret
metadata:
    name: {{ include "adictiz-events-api.fullname" . }}-jwt-keys
    labels:
    {{- include "adictiz-events-api.labels" . | nindent 4 }}
type: Opaque
data:
    private.pem: {{ .Values.php.jwt.secretKey | b64enc | quote }}
    public.pem: {{ .Values.php.jwt.publicKey | b64enc | quote }}
