apiVersion: v1
kind: Secret
metadata:
    name: {{ include "adictiz-events-api.fullname" . }}
    labels:
    {{- include "adictiz-events-api.labels" . | nindent 4 }}
type: Opaque
data:
    DATABASE_URL: {{ printf "pgsql://%s:%s@%s-postgresql:%s/%s?charset=utf8" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Release.Name (toString .Values.postgresql.primary.service.ports.postgresql) .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
    APP_SECRET: {{ .Values.php.env.appSecret | default (randAlphaNum 40) | b64enc | quote }}
    JWT_PASSPHRASE: {{ .Values.php.jwt.passphrase | default (randAlphaNum 64) | b64enc | quote }}
