apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "adictiz-events-api.serviceAccountName" . }}
    labels:
    {{- include "adictiz-events-api.labels" . | nindent 8 }}
automountServiceAccountToken: true
