apiVersion: v1
kind: Service
metadata:
    name: {{ include "adictiz-events-api.fullname" . }}
    labels:
        {{- include "adictiz-events-api.labels" . | nindent 4 }}
spec:
    type: NodePort
    ports:
        -   port: 9000
            targetPort: http
            protocol: TCP
            name: http
    selector:
    {{- include "adictiz-events-api.selectorLabels" . | nindent 8 }}
