services:
    _defaults:
        autowire: true
        autoconfigure: true

    Adictiz\Tests\Behat\:
        resource: '../tests/Behat/*'

    behatch.http_call.request:
        class: Behatch\HttpCall\Request
        arguments:
            - '@behat.mink'
        public: false
